name: Atualizar Canais VivoPlay a cada hora

on:
  schedule:
    - cron: '0 * * * *'  # A cada hora
  workflow_dispatch:

jobs:
  update-vivoplay:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Pra evitar warning de versão de engine

      - name: Instalar dependências (pular postinstall)
        run: SKIP_POSTINSTALL=true npm install

      - name: Atualizar canais VivoPlay
        run: |
          npm run channels:parse --- --config=./sites/vivoplay.com.br/vivoplay.com.br.config.js --output=./sites/vivoplay.com.br/vivoplay.com.br.channels.xml

      - name: Commit e push se houver alterações
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add sites/vivoplay.com.br/vivoplay.com.br.channels.xml
          if git diff --cached --quiet; then
            echo "Nenhuma mudança detectada"
          else
            git commit -m "Atualização automática VivoPlay - $(date '+%Y-%m-%d %H:%M:%S')"
            git push
