name: Atualizar EPG VivoPlay a cada 1 hora

on:
  schedule:
    - cron: '0 * * * *'  # a cada 1 hora
  workflow_dispatch:

jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clonar repositório original do EPG
        run: git clone --depth 1 https://github.com/iptv-org/epg.git epg-org

      - name: Rodar comando para atualizar channels
        working-directory: ./epg-org
        run: |
          npm install
          npm run channels:parse --- --config=./sites/vivoplay.com.br/vivoplay.com.br.config.js --output=../../guide.xml

      - name: Ajustar timezone do guide.xml para +3
        run: |
          sed -E -i 's/(start="([0-9]{14}) )\+0000"/echo "\1+0300"/ge' ../../guide.xml
          sed -E -i 's/(stop="([0-9]{14}) )\+0000"/echo "\1+0300"/ge' ../../guide.xml

      - name: Configurar git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

      - name: Commit e Push (se houver mudanças)
        run: |
          git add guide.xml
          if git diff --cached --quiet; then
            echo "Nenhuma mudança detectada"
          else
            git commit -m "Atualização automática do EPG VivoPlay - $(date '+%Y-%m-%d %H:%M:%S')"
            git push
          fi
