name: Atualizar EPG VivoPlay a cada 1 hora

on:
  schedule:
    - cron: '0 * * * *'  # A cada 1 hora
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do seu repositório
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Clonar o repositório original do iptv-org/epg
        run: |
          git clone --depth 1 https://github.com/iptv-org/epg.git epg-org

      - name: Instalar dependências do projeto epg-org
        run: |
          cd epg-org
          npm install

      - name: Rodar atualização do VivoPlay
        run: |
          cd epg-org
          npm run channels:parse --- --config=./sites/vivoplay.com.br/vivoplay.com.br.config.js --output=../guide.xml

      - name: Commit e push (se houver alterações)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add guide.xml
          if git diff --cached --quiet; then
            echo "Nenhuma mudança detectada"
          else
            git commit -m "Atualização automática VivoPlay - $(date '+%Y-%m-%d %H:%M:%S')"
            git push
