name: Atualizar EPG VivoPlay a cada 1 hora

on:
  schedule:
    - cron: '0 * * * *'  # a cada 1 hora
  workflow_dispatch:

jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório iptv-org/epg
        run: git clone --depth 1 https://github.com/iptv-org/epg.git epg-org

      - name: Rodar parser do vivoplay e gerar guide.xml
        run: |
          cd epg-org
          npm install
          npm run channels:parse --- --config=./sites/vivoplay.com.br/vivoplay.com.br.config.js --output=../guide.xml

      - name: Fazer commit e push se tiver alteração
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add guide.xml
          if git diff --cached --quiet; then
            echo "Nenhuma mudança detectada"
          else
            git commit -m "Atualização automática VivoPlay - $(date '+%Y-%m-%d %H:%M:%S')"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:master
          fi
