name: Atualizar canais VivoPlay a cada hora

on:
  schedule:
    - cron: '0 * * * *'  # a cada hora
  workflow_dispatch:

jobs:
  update_channels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do seu repositório
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Atualizar lista de canais VivoPlay
        run: |
          npm run channels:parse --- --config=./sites/vivoplay.com.br/vivoplay.com.br.config.js --output=./sites/vivoplay.com.br/vivoplay.com.br.channels.xml

      - name: Commit e push se houver mudanças
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add sites/vivoplay.com.br/vivoplay.com.br.channels.xml
          if git diff --cached --quiet; then
            echo "Nenhuma mudança detectada"
          else
            git commit -m "Atualização automática da lista de canais VivoPlay - $(date '+%Y-%m-%d %H:%M:%S')"
            git push
