name: Atualizar EPG VivoPlay a cada hora

on:
  schedule:
    - cron: '0 * * * *'  # Executa a cada 1 hora
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório com permissão de push
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Importante para permitir o push com o GITHUB_TOKEN

      - name: Clonar o repositório oficial iptv-org/epg
        run: git clone --depth=1 https://github.com/iptv-org/epg.git

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: |
          cd epg
          npm install

      - name: Gerar o guide.xml apenas da VivoPlay
        run: |
          cd epg
          npm run grab --- --site=vivoplay.com.br --output=guide.xml

      - name: Copiar o guide.xml para o repositório
        run: cp epg/guide.xml .

      - name: Commit e push (se houver alterações)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add guide.xml
          if git diff --cached --quiet; then
            echo "Nenhuma mudança detectada"
          else
            git commit -m "Atualização automática do EPG VivoPlay"
            git push
          fi
