name: Atualizar EPG VivoPlay

on:
  schedule:
    - cron: '0 * * * *'  # Toda hora no minuto zero
  workflow_dispatch:

jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar o repositório original do iptv-org/epg (código e configs)
      - name: Clonar repositório iptv-org/epg
        run: |
          git clone https://github.com/iptv-org/epg.git epg
          cd epg
          npm install

      # 2. Rodar o comando para atualizar o EPG do vivoplay
      - name: Atualizar EPG vivo play
        run: |
          cd epg
          npm run grab --- --site=vivoplay.com.br
          npm run channels:parse --- --config=./sites/vivoplay.com.br/vivoplay.com.br.config.js --output=../guide.xml

      # 3. Fazer commit e push do guide.xml atualizado para seu repositório
      - name: Commit e push guide.xml atualizado
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add guide.xml
          if git diff --cached --quiet; then
            echo "Nenhuma mudança detectada"
          else
            git commit -m "Atualização automática do EPG VivoPlay - $(date '+%Y-%m-%d %H:%M:%S')"
            git push origin HEAD:main
          fi
